[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"
dim_foreground = "#a4b9ef"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.dim]
black = "#14151b"
red = "#ff3333"
green = "#22fa59"
yellow = "#e7f65a"
blue = "#9961f7"
magenta = "#ff4da0"
cyan = "#5ee4fc"
white = "#e2e2dc"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.line_indicator]
background = "None"
foreground = "None"

