[solarized.bright]
black = "#cdc6df"
blue = "#657b83"
cyan = "#586e75"
green = "#93a1a1"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#002b36"
yellow = "#839496"

[solarized.cursor]
cursor = "#586e75"
text = "#fdf6e3"

[solarized.normal]
black = "#eee8d5"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#073642"
yellow = "#b58900"

[solarized.primary]
background = "#fdf5e3"
bright_foreground = "#073642"
foreground = "#506879"

